# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run application tests"
  lane :test do
    run_tests(workspace: "ChuckNorris.xcworkspace",
              devices: ["iPhone Xs"],
              scheme: "ChuckNorris")
  end

  desc "Run code coverage"
  lane :codecoverage do |options|
    xcov(
      workspace: "ChuckNorris.xcworkspace",
      scheme: "ChuckNorris",
      output_directory: "xcov_output",
      include_targets: "ChuckNorris.app"
    ) 
  end
end
